apiVersion: v2
name: semantic-explorer
description: A Helm chart for deploying Semantic Explorer in Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.24.0-0"

maintainers:
  - name: Jonathan Poisson

sources:
  - https://github.com/FishySoftware/semantic-explorer

dependencies:
  - name: redis-ha
    alias: redis
    version: "4.35.5"
    repository: https://dandydeveloper.github.io/charts
    condition: redis.enabled
  - name: nats
    version: "1.2.x"
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: qdrant
    version: "0.8.x"
    repository: https://qdrant.github.io/qdrant-helm
    condition: qdrant.enabled
  - name: minio
    version: "5.2.x"
    repository: https://charts.min.io/
    condition: minio.enabled
