apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
    editable: true
    uid: prometheus

  - name: Quickwit-Traces
    type: jaeger
    access: proxy
    url: http://localhost:7280
    jsonData:
      nodeGraph:
        enabled: true
    editable: true
    uid: quickwit-traces

  - name: Quickwit-Logs
    type: loki
    access: proxy
    url: http://localhost:7280/api/v1/otel-logs-v0_7
    jsonData:
      maxLines: 5000
      timeout: 60
    editable: true
    uid: quickwit-logs
