apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 10s
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
    editable: true
    uid: prometheus

  - name: Quickwit-Traces
    type: jaeger
    access: proxy
    url: http://quickwit:7281
    jsonData:
      nodeGraph:
        enabled: true
    editable: true
    uid: quickwit-traces

  - name: Quickwit-Logs
    type: loki
    access: proxy
    url: http://quickwit:7280/api/v1/otel-logs-v0_7
    jsonData:
      maxLines: 5000
      timeout: 60
    editable: true
    uid: quickwit-logs

  - name: Quickwit
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit:7280/api/v1
    jsonData:
      index: "otel-logs-v0_7"
      logMessageField: "body.message"
      logLevelField: "severity_text"
    editable: true
    uid: quickwit

  - name: Quickwit-Traces-Data
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit:7280/api/v1
    jsonData:
      index: "otel-traces-v0_7"
      logMessageField: "span_name"
    editable: true
    uid: quickwit-traces-data

  - name: Postgres-Audit
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    database: explorer
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      database: explorer
    secureJsonData:
      password: password
    editable: true
    uid: postgres-audit
