{{- if .Values.api.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "semantic-explorer.api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.api.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
