{{- if and .Values.dex.enabled (not .Values.dex.external.enabled) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ eq (toString .Values.dex.config.storage.type) "kubernetes" }}
metadata:
  name: {{ include "semantic-explorer.dex.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.dex.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
