{{- if and .Values.embeddingInferenceApi.enabled .Values.embeddingInferenceApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "semantic-explorer.embeddingInferenceApi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.embeddingInferenceApi.labels" . | nindent 4 }}
  {{- with .Values.embeddingInferenceApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
