{{- if and .Values.inferenceApi.enabled .Values.inferenceApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "semantic-explorer.inferenceApi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.inferenceApi.labels" . | nindent 4 }}
  {{- with .Values.inferenceApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
