{{- if and .Values.llmInferenceApi.enabled .Values.llmInferenceApi.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "semantic-explorer.llmInferenceApi.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.llmInferenceApi.labels" . | nindent 4 }}
  {{- with .Values.llmInferenceApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
