{{- if and .Values.workerVisualizationsPy.enabled .Values.workerVisualizationsPy.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: {{ include "semantic-explorer.workerVisualizationsPy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semantic-explorer.workerVisualizationsPy.labels" . | nindent 4 }}
  {{- with .Values.workerVisualizationsPy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
